maintainers:
- billimek
- bjw-s
- carpenike
- onedr0p
- angelnu
labels: true
empty_description_check:
  enabled: true
  enforced: false
branch_destroyer:
  enabled: true
  protected_branches:
  - main
pull_requests:
  automated_merge: false
  cats_enabled: true
  dogs_enabled: true
  allow_approval: true
