---

blank_issues_enabled: false
contact_links:
- name: Discuss on GitHub
  url: https://github.com/k8s-at-home/organization/discussions
  about: Ask and answer questions here
- name: Discuss on Discord
  url: https://discord.com/invite/sTMX7Vh
  about: Join our Discord community
